### ISSUE TITLE
job: get_job: builder error: unsupported pair

### ISSUE THREAD

**Issue by nixxholas** [lquerel/gcp-bigquery-client#12]
Stacktrace: `Oct 28 17:51:18.337 ERROR solana_skip_indexer::helpers::bq_utils: FATAL! builder error: unsupported pair`

All we got from the client was **builder error: unsupported pair**

Access token was a vector of u8 with a size of 990.
The rest of the data required to execute get_job is as shown below

![Screenshot 2021-10-28 at 5 53 15 PM](https://user-images.githubusercontent.com/4703269/139232811-9328c6ff-e25f-4a21-bed5-50ba3cc68883.png)

### Rationale
The purpose of getting this fixed is not just to keep it working, but to allow users of jobs be able to check the job's status again should it be in 'RUNNING' or 'PENDING' state after awaiting for the initial 'insert' or delete' or etc. function.

**Comment by lquerel** [comment]
Although the existing API could be simplified, you can implement what you need by following the example below.

https://github.com/lquerel/gcp-bigquery-client/blob/main/examples/bq_load_job.rs

The issue was not in the client itself but in the initial example. Instead of passing a download url, the JobConfigurationLoad object was expecting an URI (gs://<bucket>/<file>.

Let me know if everything is working now for you.
