### ISSUE TITLE
The tabledata.list API method return type might be wrong?

### ISSUE THREAD

**Issue by enricozb** [lquerel/gcp-bigquery-client#66]
The [TableDataApi::list](https://docs.rs/gcp-bigquery-client/latest/gcp_bigquery_client/tabledata/struct.TableDataApi.html#method.list) method (source here):
```rust
    pub async fn list(
        &self,
        project_id: &str,
        dataset_id: &str,
        table_id: &str,
        parameters: ListQueryParameters,
    ) -> Result<TableDataInsertAllResponse, BQError> {
```
returns a `TableDataInsertAllResponse`. Shouldn't this return the rows?

**Comment by lquerel** [comment]
You are correct, this method should not return a TableDataInsertAllResponse.
I don't know for certain if I will be able to fix that soon since my to-do list for other projects is already extensive.
If you have the bandwidth, please don't hesitate to submit a PR with the corresponding fix, and I will review it.
Thanks.
